### ISSUE TITLE
New Orbot Beta Fails to Work in Second Profile

### ISSUE THREAD

**Issue by cm157** [guardianproject/orbot#437]
Orbot 16.4.0-RC-1-Tor-0.4.4.6

Android 11 (GrapheneOS)

Device: Pixel 3 & Pixel 4a

Config: VPN Mode + Always On VPN + Block if not connected

Previously, you could run Orbot in two user profiles simultaneously with no problem. Now If you attempt to run Orbot is a second profile without shutting down the first user profile Orbot will crash as soon as you press start.

**Comment by bitmold** [comment]
I think I noticed something similar last night running Orbot and the unreleased Ornot Mini (found in this repository) at the same time. I'll see if i can reproduce thr crash...

**Comment by n8fr8** [comment]
Hmm... that is interesting that that ever worked at all. Is it the VPN mode that is causing the problem, or just Tor itself?

**Comment by cm157** [comment]
> Hmm... that is interesting that that ever worked at all. Is it the VPN mode that is causing the problem, or just Tor itself?

I used Orbot simultaneously in the admin + two user profiles with no problem since 2019. I will investigate it more carefully to determine whether the result is affected by configuration options you mentioned above.

**Comment by user9922-1** [comment]
The problem is some pluggable transports bind on static ports:

`02-23 03:11:39.174 24104 24142 I GoLog   : VERSION 1
02-23 03:11:39.175 24104 24142 I GoLog   : CMETHOD-ERROR meek_lite listen tcp 127.0.0.1:47352: bind: address already in use
02-23 03:11:39.175 24104 24142 I GoLog   : CMETHOD-ERROR obfs2 listen tcp 127.0.0.1:47353: bind: address already in use
02-23 03:11:39.175 24104 24142 I GoLog   : CMETHOD-ERROR obfs3 listen tcp 127.0.0.1:47354: bind: address already in use
02-23 03:11:39.175 24104 24142 I GoLog   : CMETHOD-ERROR obfs4 listen tcp 127.0.0.1:47351: bind: address already in use`

You run Orbot in one of the profiles and when you run it in a different one it obviously crashes because the ports are still in use. It's an easy fix, catch the exception and try using a different port.

**Comment by tladesignz** [comment]
Ok, so I did an experimental rework of IPtProxy here:
https://github.com/tladesignz/IPtProxy/tree/experiment/port_collision

Unfortunately can't build for Android currently, due to some stupid bug in Go again. Please try yourself!

The logic is now, that IPtProxy tries to find free ports and use that, before it starts the transports.
It will return the decided-upon port synchronously and also provide it via a getter method.

There might be a race condition, and something else uses the port in the meantime. On the other hand, this was easy to implement and avoids reusing another instance, which might also be a security problem.

From a security perspective, doing a callback (seems Gomobile actually supports interfaces only) might be the only "right" thing. However, that makes the usage quite different, as you first would need to wait for the start of the transport and then reconfigure Tor.

@n8fr8, please tell me what you think of this!

**Comment by n8fr8** [comment]
This should be fixed in the latest Orbot beta
https://github.com/guardianproject/orbot/releases/tag/16.5.1-BETA-2a-tor.0.4.5.9

**Comment by bitmold** [comment]
I've been going through the backlog and seeing if old bugs still exists to users on the play store because the release there is Orbot 16.4.0-RC-2a-tor-0.4.4.6 which is about 7 months old and still has support for v2 onion services 

@n8fr8 is there a plan to release a newer version anytime soon. Also I'm wondering if you tested this feature in the use case described here. I remember testing it by deploying app and app-mini to the same user profile and it worked.
